testing workflow

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -36,6 +36,17 @@ runs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
 
+    - name: Debug tag input
+      shell: bash
+      run: |
+        echo "Received tag: '${{ inputs.tag }}'"
+        echo "Registry: '${{ inputs.registry }}'"
+        echo "Image name: '${{ inputs.image-name }}'"
+        if [ -z "${{ inputs.tag }}" ]; then
+          echo "ERROR: tag input is empty!"
+          exit 1
+        fi
+
     - name: Log in to Docker Registry
       uses: docker/login-action@v3
       with:
